# development:
#   cloud_name: gmg-archive-project
#   api_key: '119581295779122'
#   api_secret: mgoEaHFgQ1MqFUeOA1C3PFyS-0M
#   # enhance_image_tag: true
#   # static_file_support: false
# production:
#   cloud_name: gmg-archive-project
#   api_key: '119581295779122'
#   api_secret: mgoEaHFgQ1MqFUeOA1C3PFyS-0M
#   # enhance_image_tag: true
#   # static_file_support: true
# test:
#   cloud_name: gmg-archive-project
#   api_key: '119581295779122'
#   api_secret: mgoEaHFgQ1MqFUeOA1C3PFyS-0M
#   # enhance_image_tag: true
#   # static_file_support: false
